name: Auto Format Code

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write access to the repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Personal access token is needed to push back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npm run format

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || (git add -A && git commit -m "style: format code with prettier" && git push)
